# Generated by Django 4.2.5 on 2023-09-30 12:04

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_name_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=stdimage.models.StdImageField(default='', force_min_size=False, upload_to='users/', variations={'50x50': {'crop': True, 'height': 50, 'width': 50}}, verbose_name='Photo de profile'),
        ),
    ]
