# Generated by Django 4.2.5 on 2023-10-04 11:37

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_quiz_user_quiz_created_by_quiz_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='taken_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
