# Generated by Django 4.2.5 on 2023-10-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_likedquiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='name',
        ),
    ]
