# Generated by Django 4.2.5 on 2023-10-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_option_option_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(default='#7fc97f', max_length=7),
        ),
    ]
