# Generated by Django 4.2.5 on 2023-10-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_topic_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='color',
            field=models.CharField(default='#1f77b4', max_length=7),
        ),
    ]
