# Generated by Django 4.2.5 on 2023-11-06 14:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_topic_color_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_image'),
        ),
    ]
